"""empty message

Revision ID: 2abf5f35de7a
Revises: 114e190d023b
Create Date: 2019-03-27 15:29:25.270920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abf5f35de7a'
down_revision = '114e190d023b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('copyright', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###
