"""empty message

Revision ID: 16570ac1e0d3
Revises: 00132c809079
Create Date: 2020-02-11 14:47:02.425642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16570ac1e0d3'
down_revision = '00132c809079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('pv', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blog_post_pv'), 'blog_post', ['pv'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_post_pv'), table_name='blog_post')
    op.drop_column('blog_post', 'pv')
    # ### end Alembic commands ###
