"""empty message

Revision ID: d5730252ea3a
Revises: 16570ac1e0d3
Create Date: 2020-02-12 10:48:49.198220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5730252ea3a'
down_revision = '16570ac1e0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('release', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_history_time'), 'project_history', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_history_time'), table_name='project_history')
    op.drop_table('project_history')
    # ### end Alembic commands ###
